# ----------- CONFIGURABLE START -----------
title:            "ThemeGoal | Shopify Theme"
description:      "ThemeGoal | Shopify Theme"
url:              https://themegoal.github.io # 域名
signoff:          "ThemeGoal" # Your name
facebook_appid:   #themegoal
#google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 15
paginate_path: "themegoal:num"
gems: [jekyll-paginate]
links:
  - name:         首页
    url:          /
    external:     false
  - name:         书籍
    url:          /book
    external:     false
  - name:         旅游
    url:          /road
    external:     false
  - name:         归档
    url:          /archives
    external:     false
  - name:         标签
    url:          /tags
    external:     false
  - name:         关于
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
