# ----------- CONFIGURABLE START -----------
title:            "ThemeGoal | eCommerce Theme"
description:      "ThemeGoal | eCommerce Theme "
url:              https://themegoal.github.io # 域名
signoff:          "ThemeGoal" # Your name
facebook_appid:   #themegoal
#google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 6
paginate_path: "themegoal:num"
#paginatepath: ['opencart/page/:num','shopify/page/:num','magento/page/:num']
gems: [jekyll-paginate]
links:
  - name:         Home
    url:          /
    external:     false
  - name:         Shopify
    url:          /shopify
    external:     false
  - name:         Magento
    url:          /magento
    external:     false
  - name:         OpenCart
    url:          /opencart
    external:     false
  - name:         PrestaShop
    url:          /prestashop
    external:     false

# ------------ CONFIGURABLE END ------------

permalink:        /:title.html
#permalink:        /:categories/:title.html
#permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
