# ----------- CONFIGURABLE START -----------
title:            "ThemeGoal | Shopify Theme"
description:      "ThemeGoal | Shopify Theme"
url:              https://themegoal.github.io # 域名
signoff:          "ThemeGoal" # Your name
facebook_appid:   #themegoal
#google_analytics: UA-101222464-1
share:            true 
# 分页
paginate: 6
paginate_path: "themegoal:num"
gems: [jekyll-paginate]
links:
  - name:         Home
    url:          /
    external:     false
  - name:         Shopify
    url:          /shopify
    external:     false
  - name:         Book
    url:          /book
    external:     false

  - name:         Archives
    url:          /archives
    external:     false
  - name:         Tags
    url:          /tags
    external:     false
# ------------ CONFIGURABLE END ------------

permalink:        /:categories/:title.html
#permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
